version: '2'

networks:
  bd-network:
    driver: bridge
  app-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:


services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=jabreu
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=products_db
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - bd-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=abreu.jonathan220@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123
    networks:
      - bd-network
    ports:
      - "8080:80"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - app-network
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - app-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"
    networks:
      - app-network

  tempo:
    image: grafana/tempo:latest
    command: 
      - --config.file=/etc/tempo.yml
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"
      - "4317"
    networks:
      - app-network

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - app-network

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      - app-network

